from pathlib import Path
root=Path(__file__).resolve().parents[1]
checks=[]
def add(name,ok): checks.append((name,bool(ok)))
cpp=(root/'matlab/phys_mpc/airdropx_jsbsim_wind_oracle_mex.cpp').read_text()
mission=(root/'matlab/airdrop/airdropx_wind_airdrop_mission_v121.m').read_text()
runner=(root/'run_wind_airdrop_v121_D.ps1').read_text()
predictor=(root/'matlab/airdrop/airdropx_airdrop_predict_impact_v121.m').read_text()
truth=(root/'matlab/airdrop/airdropx_airdrop_truth_impact_v121.m').read_text()
add('separate wind oracle source', 'airdropx_jsbsim_wind_oracle_mex.cpp' in (root/'matlab/phys_mpc/build_airdropx_jsbsim_wind_oracle_v121.m').read_text())
add('continuous start command', 'start_continuous' in cpp and 'startContinuous' in cpp)
add('continuous step command', 'step_continuous' in cpp and 'stepContinuous' in cpp)
add('wind oracle version', 'wind-continuous oracle v1.2.1' in cpp)
add('wind diag groundspeed', 'groundspeed_mps' in cpp and 'v_north_mps' in cpp)
add('wind diag position', 'pos_n_m' in cpp and 'delta_n_m' in cpp)
add('cfg cannot reverse', 'Continuous payload cfg cannot decrease' in cpp)
add('predictor no truth argument', 'truth' not in predictor.lower())
add('truth isolated scoring function', 'scoring-only' in truth.lower() and 'airdropx_wind_profile_v111' in truth)
add('four targets', "targets=opts.TargetStart_m+(0:3)'*opts.TargetSpacing_m" in mission)
add('real cfg increment on release', 'cfg=cfg+1' in mission)
add('estimated wind guidance', 'wGuide=WindEst(k)' in mission and 'rGuide=WindRate(k)' in mission)
add('baseline does not use GPS wind implicitly', 'vxGuide=sqrt(max(VaMeas^2-VzMeas^2,0))' in mission)
add('truth only after release decision', 'if shouldRelease' in mission and 'airdropx_airdrop_truth_impact_v121' in mission)
add('landing gate 20m default', 'opts.MaxLandingError_m' in mission and '= 20' in mission)
add('predicted impact gate 10m', 'opts.MaxPredictedImpactErrorAtRelease_m' in mission and '= 10' in mission)
add('wind p95 gate 0.75', 'opts.MaxWindErrorP95_mps' in mission and '= 0.75' in mission)
add('fixed horizon 100', 'Horizon=100' in mission)
add('paired aware baseline', "Mode='wind_aware'" in runner and "Mode='no_wind_baseline'" in runner)
add('max parallel 3', '[int]$MaxParallel=3' in runner)
add('serial full-chain preflight', 'SERIAL FULL-CHAIN PREFLIGHT' in runner)
add('original oracle not overwritten', 'airdropx_jsbsim_oracle_mex.cpp' not in '\n'.join(str(p) for p in root.rglob('*') if p.is_file()))
add('no bundled mex', not any(p.suffix.lower()=='.mexw64' for p in root.rglob('*')))
failed=[n for n,o in checks if not o]
for n,o in checks: print(f"{'PASS' if o else 'FAIL'} | {n}")
print(f"TOTAL {len(checks)-len(failed)}/{len(checks)} PASS")
if failed: raise SystemExit(1)
