from pathlib import Path
R=Path(__file__).resolve().parents[1]
checks=[]
def ck(name, cond):
    checks.append((name,bool(cond)))
def text(rel): return (R/rel).read_text(encoding='utf-8')
mission=text('matlab/airdrop/airdropx_wind_airdrop_mission_v134.m')
entry=text('matlab/airdrop/airdropx_wind_airdrop_entry_v134.m')
final=text('matlab/airdrop/airdropx_wind_airdrop_finalize_v134.m')
bank=text('matlab/phys_mpc/airdropx_phys_mpc_build_recovery_bank_v134.m')
run=text('run_wind_disturbance_airdrop_v134_D.ps1')
point=text('run_wind_disturbance_airdrop_point_v134_D.ps1')
install=text('install_wind_disturbance_airdrop_v134.ps1')
ck('mission function v134','function report=airdropx_wind_airdrop_mission_v134' in mission)
ck('entry calls v134 mission','airdropx_wind_airdrop_mission_v134' in entry)
ck('runner calls v134 entry','airdropx_wind_airdrop_entry_v134' in run)
ck('point calls v134 entry','airdropx_wind_airdrop_entry_v134' in point)
ck('runner calls v134 finalizer','airdropx_wind_airdrop_finalize_v134' in run)
ck('mission calls v134 recovery bank','airdropx_phys_mpc_build_recovery_bank_v134' in mission)
ck('continuous recovery assist defaults off','opts.UseContinuousRecoveryAssist (1,1) logical = false' in mission)
ck('continuous assist is explicit opt-in','if opts.UseContinuousRecoveryAssist &&' in mission)
ck('disturbance evidence thresholds present','DisturbanceMinWindConfidence' in mission and 'DisturbanceMinRateConfidence' in mission)
ck('residual clears without evidence','dHat=zeros(7,1);' in mission and '~disturbanceEvidence && ~gustLatched' in mission)
ck('base solver calm fallback','(~disturbanceEvidence && ~gustLatched)' in mission and 'airdropx_phys_mpc_solve(baseCtrl,x,warm)' in mission)
ck('abrupt gust requires confidence','strongWindEvidence=WindConfidence(k)>=opts.GustTriggerMinWindConfidence' in mission)
ck('abrupt gust requires delta','abs(deltaWindEst)>=abruptThreshold' in mission)
ck('energy absolute cap 3m','EnergyMaxAltitudeShift_m (1,1) double {mustBeNonnegative} = 3.0' in mission)
ck('energy relative cap','EnergyMaxAltitudeShiftFraction (1,1) double {mustBeNonnegative} = 0.02' in mission)
ck('energy cap uses nominal altitude','min(opts.EnergyMaxAltitudeShift_m,opts.EnergyMaxAltitudeShiftFraction*max(abs(baseCtrl.xref(1)),1))' in mission)
ck('Iyy cfg0 bias captured','iyyReferenceBias_kgm2=oracleInitialIyy_kgm2-expectedIyy(1)' in mission)
ck('Iyy ref bias applied to cfg schedule','expectedIyy(Cfg(vv)+1)+iyyReferenceBias_kgm2' in mission)
ck('Iyy remaining error still formal','metrics.Iyy_match_error_max_kgm2<=1e-2' in mission)
ck('Iyy bias logged','metrics.Iyy_reference_bias_kgm2=iyyReferenceBias_kgm2' in mission)
ck('plot interpreter none','"Interpreter","none"' in mission)
ck('input snap tolerance retained','InputSnapTolerance' in mission and 'localSnapPhysicalInput' in mission)
ck('hard bounds retained','gate.input_bounds=' in mission)
ck('recovery bank Va emphasis','[0.85;4.0;0.90;0.90;1.20;1.0;1.0]' in bank)
ck('recovery bank elevator cheaper','[0.55;0.85]' in bank)
ck('same recovery bank all cfg','for cfg=0:4' in bank)
ck('runner hidden windows',"WindowStyle='Hidden'" in run)
ck('point hidden windows',"WindowStyle='Hidden'" in point)
ck('show windows override retained','ShowChildWindows' in run and 'ShowChildWindows' in point)
ck('stable point output root','physics_mpc_v134_stable_energy_recovery_point' in point)
ck('stable full output root','physics_mpc_v134_stable_energy_recovery_airdrop_validation' in run)
ck('final stable summary name','wind_stable_energy_recovery_validation_summary.txt' in final and 'wind_stable_energy_recovery_validation_summary.txt' in run)
ck('installer installs v134 runners','run_wind_disturbance_airdrop_v134_D.ps1' in install and 'run_wind_disturbance_airdrop_point_v134_D.ps1' in install)
ck('no mex shipped',not any(R.rglob('*.mexw64')))
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL'),n)
print(f'RESULT {sum(v for _,v in checks)}/{len(checks)} PASS')
if failed: raise SystemExit(1)
