function report = airdropx_physics_mpc_preflight(varargin)
%AIRDROPX_PHYSICS_MPC_PREFLIGHT Check only the files needed by Physics-MPC v1.5.
opts=local_options(varargin{:});root=char(string(opts.ProjectRoot));if isempty(root),a=fileparts(mfilename('fullpath'));root=fileparts(fileparts(a));end
v32=char(string(opts.ExistingV32Root));if isempty(regexp(v32,'^[A-Za-z]:[\\/]|^/|^\\\\','once')),v32=fullfile(root,v32);end
items={ ...
 'MQ9 aircraft XML',fullfile(root,'aircraft','MQ9_Reaper','MQ9_Reaper.xml'); ...
 'MQ9 controls XML',fullfile(root,'aircraft','MQ9_Reaper','Controls.xml'); ...
 'MQ9 IC template',fullfile(root,'aircraft','MQ9_Reaper','reset_20m.xml'); ...
 'engine XML',fullfile(root,'engine','TPE331-10.xml'); ...
 'JSBSim MEX',fullfile(root,'matlab','sfunc_jsbsim','sfun_airdropx_jsbsim.mexw64'); ...
 'ID model',fullfile(root,'matlab','mpc','airdropx_mpc_id.slx'); ...
 'closed-loop model',fullfile(root,'matlab','mpc','airdropx_mpc_closed_loop.slx'); ...
 'v32 runtime',fullfile(root,'matlab','mpc_auto','airdropx_v32_run_closed_loop.m'); ...
 'v32 scheduler S-function',fullfile(root,'matlab','mpc_auto','sfun_airdropx_v32_mpc_controller.m')};
for v=double(opts.SpeedNodesMps(:)).'
 items(end+1,:)={sprintf('trim bank V%.1f',v),fullfile(v32,'knowledge_bank','physics',sprintf('V%06.3f',v),'v32_trim_bank.mat')}; %#ok<AGROW>
end
name=string(items(:,1));path=string(items(:,2));exists=false(size(name));for k=1:numel(name),exists(k)=isfile(path(k));end
T=table(name,path,exists,'VariableNames',{'item','path','exists'});disp(T);
report=struct('pass',all(exists),'table',T,'missing',T(~exists,:));
if report.pass,fprintf('[PHYS-MPC] preflight PASS (NO-MEX mode). Existing MEX/model/trim files are sufficient; no compilation is required.\n');else,fprintf(2,'[PHYS-MPC] preflight FAIL: %d required files are missing.\n',height(report.missing));end
end
function opts=local_options(varargin)
opts.ProjectRoot="";opts.ExistingV32Root="matlab/results/mpc_auto_v32_clean";opts.SpeedNodesMps=[45;50;55];
if mod(numel(varargin),2)~=0,error('Options must be name-value pairs.');end
for i=1:2:numel(varargin),n=string(varargin{i});if ~isfield(opts,n),error('Unknown option: %s',n);end,opts.(n)=varargin{i+1};end
end
