function result = airdropx_auto_full_auto(varargin)
%AIRDROPX_AUTO_FULL_AUTO One-command trim -> clean ID -> identify -> closed-loop tuning.
%
% Trim and ID excitation run at a safe altitude so poor open-loop candidates
% have room to settle. The altitude deviation model is then shifted back to
% TargetAltitudeM for the real closed-loop MPC test.

opts = local_options(varargin{:});
thisDir = fileparts(mfilename("fullpath"));
matlabDir = fileparts(thisDir);
addpath(matlabDir, fullfile(matlabDir,"mpc"), thisDir);

root = string(opts.OutputRoot);
if strlength(root)==0
    root = string(fullfile(matlabDir,"results","mpc_auto_full_auto_" + ...
        string(datetime("now","Format","yyyyMMdd_HHmmss"))));
end
if ~isfolder(root), mkdir(root); end

fprintf("\n=== STAGE 1/3: automatic trim search (pitch/elevator/throttle) ===\n");
if opts.DoFindTrim
    trimRes = airdropx_auto_find_trim( ...
        "ProjectRoot", opts.ProjectRoot, ...
        "OutputMat", fullfile(root,"auto_trim_bank.mat"), ...
        "WorkRoot", fullfile(root,"trim_search"), ...
        "ReuseVerifiedTrim", opts.ReuseVerifiedTrim, ...
        "ReuseFailedAsWarmStart", opts.ReuseFailedAsWarmStart, ...
        "PreviousTrimMat", opts.PreviousTrimMat, ...
        "CheckpointMat", opts.TrimCheckpointMat, ...
        "TargetAltitudeM", opts.TargetAltitudeM, ...
        "TargetAirspeedMps", opts.TargetAirspeedMps, ...
        "SearchAltitudeM", opts.TrimSearchAltitudeM, ...
        "StopTimeS", opts.TrimStopTimeS, "RecordStartS", opts.TrimRecordStartS, ...
        "MaxObjectiveEvaluations", opts.TrimMaxObjectiveEvaluations, ...
        "PitchRange", opts.TrimPitchRange, ...
        "UseParallel", opts.TrimUseParallel);
    trimBank = trimRes.trim_bank;
else
    if isempty(opts.TrimBank), error("DoFindTrim=false requires TrimBank."); end
    trimRes = [];
    trimBank = opts.TrimBank;
end
fprintf("Automatic trim pitch cfg0..4 = %s deg\n", mat2str(arrayfun(@(s)s.pitch_deg,trimBank(:)).',4));

if opts.DoGenerateCleanIdData
    fprintf("\n=== STAGE 2/3: generate clean DirectIdMode ID data at safe altitude + n4sid ===\n");
else
    fprintf("\n=== STAGE 2/3: rebuild iddata from supplied CSV + n4sid ===\n");
end
train = airdropx_auto_train_all( ...
    "ProjectRoot", opts.ProjectRoot, ...
    "OutputRoot", fullfile(root,"identification"), ...
    "DataRoot", opts.DataRoot, ...
    "TrimBank", trimBank, ...
    "DoFindTrim", false, "DoGenerateData", opts.DoGenerateCleanIdData, ...
    "RunsPerConfig", opts.RunsPerConfig, ...
    "StopTimeS", opts.IdStopTimeS, "RecordStartS", opts.IdRecordStartS, ...
    "IdentificationAltitudeM", opts.IdentificationAltitudeM, ...
    "EstimateOperatingPointFromCsv", ~logical(opts.DoGenerateCleanIdData), ...
    "Orders", opts.Orders, "RefineWithSsest", opts.RefineWithSsest, ...
    "SsestMaxIterations", opts.SsestMaxIterations, ...
    "PredictionHorizon", 20, "ControlHorizon", 6);

fprintf("\n=== STAGE 3/3: constrained real-JSBSim MPC tuning until plateau ===\n");
cases = airdropx_auto_default_eval_cases( ...
    "TargetAltitudeM", opts.TargetAltitudeM, "TargetAirspeedMps", opts.TargetAirspeedMps, ...
    "StopTimeS", opts.ClosedLoopStopTimeS);
tune = airdropx_auto_tune_until_best( ...
    "Identified", train.identified, ...
    "OutputRoot", fullfile(root,"closed_loop_tuning"), ...
    "EvaluationFcn", @airdropx_auto_eval_case, "EvaluationCases", cases, ...
    "TargetAltitudeM", opts.TargetAltitudeM, "TargetAirspeedMps", opts.TargetAirspeedMps, ...
    "StopTimeS", opts.ClosedLoopStopTimeS, ...
    "BatchEvaluations", opts.BatchEvaluations, "MaxTotalEvaluations", opts.MaxTotalEvaluations, ...
    "StallBatches", opts.StallBatches, "MinRelativeImprovement", opts.MinRelativeImprovement, ...
    "MaxSteadyAltitudeRmsM", opts.MaxSteadyAltitudeRmsM, ...
    "MaxSteadyAirspeedRmsMps", opts.MaxSteadyAirspeedRmsMps, ...
    "MaxPitchStdDeg", opts.MaxPitchStdDeg, "MaxPitchDriftDegps", opts.MaxPitchDriftDegps, ...
    "MaxSteadyVzRmsMps", opts.MaxSteadyVzRmsMps, "MaxSteadyQRmsDps", opts.MaxSteadyQRmsDps, ...
    "MinAltitudeM", opts.MinAltitudeM, "UseParallel", opts.UseParallel);

result = struct("output_root",root,"trim",trimRes,"trim_bank",trimBank,"train",train,"tuning",tune);
save(fullfile(root,"full_auto_result.mat"),"result","opts","-v7.3");
end

function opts = local_options(varargin)
opts.ProjectRoot = "";
opts.OutputRoot = "";
opts.DataRoot = "";
opts.TrimBank = [];
opts.DoFindTrim = true;
opts.TargetAltitudeM = 20.0;
opts.TargetAirspeedMps = 50.0;
opts.TrimMaxObjectiveEvaluations = 80;
opts.TrimPitchRange = [-8 20];
opts.TrimSearchAltitudeM = 200.0;
opts.TrimStopTimeS = 22.0;
opts.TrimRecordStartS = 10.0;
opts.TrimUseParallel = false;
opts.ReuseVerifiedTrim = true;
opts.ReuseFailedAsWarmStart = true;
opts.PreviousTrimMat = "";
opts.TrimCheckpointMat = "";
opts.DoGenerateCleanIdData = true;
opts.IdentificationAltitudeM = 200.0;
opts.RunsPerConfig = 5;
opts.IdStopTimeS = 30.0;
opts.IdRecordStartS = 8.0;
opts.Orders = 3:8;
opts.RefineWithSsest = false;
opts.SsestMaxIterations = 20;
opts.ClosedLoopStopTimeS = 30.0;
opts.BatchEvaluations = 15;
opts.MaxTotalEvaluations = 90;
opts.StallBatches = 2;
opts.MinRelativeImprovement = 0.01;
opts.UseParallel = false;
opts.MaxSteadyAltitudeRmsM = 1.0;
opts.MaxSteadyAirspeedRmsMps = 1.0;
opts.MaxSteadyVzRmsMps = 0.70;
opts.MaxSteadyQRmsDps = 1.0;
opts.MaxPitchStdDeg = 0.75;
opts.MaxPitchDriftDegps = 0.12;
opts.MinAltitudeM = 15.0;
if mod(numel(varargin),2)~=0, error("Options must be name-value pairs."); end
for i=1:2:numel(varargin)
    n=string(varargin{i});
    if ~isfield(opts,n), error("Unknown option: %s",n); end
    opts.(n)=varargin{i+1};
end
if ~logical(opts.DoGenerateCleanIdData) && strlength(string(opts.DataRoot))==0
    error("DataRoot is required when DoGenerateCleanIdData=false.");
end
end
