function result = airdropx_auto_smoke_cfg0_guarded(varargin)
%AIRDROPX_AUTO_SMOKE_CFG0_GUARDED One narrow real-JSBSim MPC proof test.
%
% v13 deliberately does only cfg0 nominal by default. It does NOT retrain trim,
% ID or n4sid, and it does NOT launch bayesopt. The goal is to prove one thing:
% a local deviation-coordinate MPC can stay inside the v11 ID envelope while
% controlling the real JSBSim plant through the hidden-trim bridge.

opts = local_options(varargin{:});
paths = local_paths(opts.ProjectRoot);
addpath(paths.matlabDir);
addpath(paths.mpcDir);
addpath(paths.autoDir);
addpath(paths.sfuncDir);

identifiedMat = string(opts.IdentifiedMat);
if ~isfile(identifiedMat)
    error("AirdropX:AutoMPC:MissingIdentified", "Identified plant file not found: %s", identifiedMat);
end
S = load(identifiedMat, "result");
identified = S.result;
trim0 = identified.trim_bank(1);

outputRoot = string(opts.OutputRoot);
if strlength(outputRoot) == 0
    outputRoot = string(fullfile(paths.matlabDir, "results", ...
        "mpc_auto_smoke_cfg0_v13_" + string(datetime("now", "Format", "yyyyMMdd_HHmmss"))));
end
if ~isfolder(outputRoot), mkdir(outputRoot); end

bankMat = fullfile(outputRoot, "airdropx_mpc_bank_v13.mat");
fprintf("[V13] Building guarded deviation MPC: Np=%d Nc=%d\n", opts.PredictionHorizon, opts.ControlHorizon);
bank = airdropx_auto_build_mpc_bank( ...
    "Identified", identified, ...
    "OutputMat", bankMat, ...
    "PredictionHorizon", opts.PredictionHorizon, ...
    "ControlHorizon", opts.ControlHorizon, ...
    "InputCoordinateMode", "deviation_physical", ...
    "PhysicalElevatorNominals", opts.PhysicalElevatorNominals, ...
    "ElevatorDeviationLimit", opts.ElevatorDeviationLimit, ...
    "ThrottleDeviationLimit", opts.ThrottleDeviationLimit, ...
    "ElevatorDeviationRateLimit", opts.ElevatorDeviationRateLimit, ...
    "ThrottleDeviationRateLimit", opts.ThrottleDeviationRateLimit, ...
    "OutputWeights", opts.OutputWeights, ...
    "MVWeights", opts.MVWeights, ...
    "MVRateWeights", opts.MVRateWeights, ...
    "DisableOutputDisturbanceModel", true);
physicalNom = double(bank.mpc_meta.physical_elevator_nominals(1));
if ~isfinite(physicalNom)
    error("AirdropX:AutoMPC:NoPhysicalNominal", "cfg0 physical elevator nominal is not finite.");
end

% First calibrate the hidden S-function trim for EXACTLY the initial condition
% that the closed-loop run will use. A very short DirectIdMode run is enough;
% hidden trim is a fixed offset after reset.
calDir = fullfile(outputRoot, "hidden_trim_calibration");
fprintf("[V13] Calibrating hidden elevator trim at h=%.2f m, V=%.2f m/s ...\n", ...
    opts.InitialAltitudeM, opts.InitialAirspeedMps);
cal = airdropx_auto_run_id_experiment( ...
    "ProjectRoot", paths.projectRoot, ...
    "OutputRoot", calDir, ...
    "RunId", "cfg0_hidden_trim_calibration", ...
    "ConfigId", 0, ...
    "Trim", trim0, ...
    "StopTimeS", opts.CalibrationStopTimeS, ...
    "RecordStartS", 0.0, ...
    "ExportStartS", 0.0, ...
    "ExcitationStartS", 100.0, ...
    "ElevatorAmplitude", 0.0, ...
    "ThrottleAmplitude", 0.0, ...
    "DirectIdMode", true, ...
    "KeepFixedConfigurationOnly", true, ...
    "InitialAltitudeM", opts.InitialAltitudeM, ...
    "InitialAirspeedMps", opts.InitialAirspeedMps, ...
    "InitialPitchDeg", local_default_if_nan(opts.InitialPitchDeg, trim0.pitch_deg), ...
    "InitialFlightPathDeg", opts.InitialFlightPathDeg, ...
    "TargetAltitudeM", opts.TargetAltitudeM, ...
    "TargetAirspeedMps", opts.TargetAirspeedMps);
Tc = cal.timeseries;
external = local_column(Tc, "requested_elevator_cmd");
physical = local_column(Tc, "elevator_cmd_norm");
mask = isfinite(external) & isfinite(physical) & double(Tc.time_s) <= opts.CalibrationUseUntilS;
if nnz(mask) < 3
    error("AirdropX:AutoMPC:HiddenTrimCalibration", ...
        "Not enough finite calibration samples for hidden trim.");
end
hiddenTrim = median(physical(mask) - external(mask), "omitnan");
initialDelta = physicalNom - hiddenTrim;
calibration = table(physicalNom, hiddenTrim, initialDelta, double(trim0.throttle_cmd), ...
    'VariableNames', {'physical_elevator_nominal','hidden_elevator_trim','initial_external_delta','throttle_nominal'});
writetable(calibration, fullfile(outputRoot, "hidden_trim_summary.csv"));
fprintf("[V13] physical nominal=%.6f, hidden trim=%.6f, initial external delta=%.6f\n", ...
    physicalNom, hiddenTrim, initialDelta);

% Phase 0: prove the exact same Simulink closed-loop model reproduces the
% corrected open-loop operating point when MPC authority is zero. This catches
% any remaining bridge/delay/IC wiring error before MPC is allowed to move.
preDir = fullfile(outputRoot, "cfg0_bridge_only_preflight");
preResult = airdropx_auto_run_closed_loop( ...
    "ProjectRoot", paths.projectRoot, ...
    "MpcBankMat", bankMat, ...
    "OutputRoot", preDir, ...
    "CaseId", "cfg0_bridge_only_preflight", ...
    "StopTimeS", opts.PreflightStopTimeS, ...
    "FixedConfigId", 0, ...
    "FixedDropTotal", 0.0, ...
    "FixedDropStartS", opts.PreflightStopTimeS + 100.0, ...
    "InitialAltitudeM", opts.InitialAltitudeM, ...
    "InitialAirspeedMps", opts.InitialAirspeedMps, ...
    "InitialPitchDeg", local_default_if_nan(opts.InitialPitchDeg, trim0.pitch_deg), ...
    "InitialFlightPathDeg", opts.InitialFlightPathDeg, ...
    "InitialElevatorDelta", initialDelta, ...
    "InitialThrottleCmd", trim0.throttle_cmd, ...
    "HiddenElevatorTrim", hiddenTrim, ...
    "MpcEnableTimeS", opts.PreflightStopTimeS + 100.0, ...
    "MpcAuthorityScale", 0.0, ...
    "TargetAltitudeM", opts.TargetAltitudeM, ...
    "TargetAirspeedMps", opts.TargetAirspeedMps, ...
    "TargetPitchDeg", trim0.pitch_deg, ...
    "UseTrimPitchReference", 1.0);
preSummary = local_diagnostics(preResult.timeseries, physicalNom, trim0.throttle_cmd, opts);
writetable(preSummary, fullfile(outputRoot, "bridge_only_preflight_summary.csv"));
if preSummary.hard_fail || preSummary.max_bridge_elevator_error > opts.MaxBridgeError || ...
        preSummary.max_bridge_throttle_error > opts.MaxBridgeError
    error("AirdropX:AutoMPC:BridgePreflightFailed", ...
        ['Bridge-only preflight failed before MPC was allowed to move. ' ...
         'Inspect cfg0_bridge_only_preflight/closed_loop_timeseries.csv; do not tune MPC.']);
end
fprintf("[V13] Bridge-only preflight PASS. Enabling guarded MPC authority %.2f.\n", opts.MpcAuthorityScale);

caseDir = fullfile(outputRoot, "cfg0_nominal");
simResult = airdropx_auto_run_closed_loop( ...
    "ProjectRoot", paths.projectRoot, ...
    "MpcBankMat", bankMat, ...
    "OutputRoot", caseDir, ...
    "CaseId", "cfg0_nominal_v13", ...
    "StopTimeS", opts.StopTimeS, ...
    "FixedConfigId", 0, ...
    "DropMode", 1.0, ...
    "FixedDropTotal", 0.0, ...
    "FixedDropStartS", opts.StopTimeS + 100.0, ...
    "InitialAltitudeM", opts.InitialAltitudeM, ...
    "InitialAirspeedMps", opts.InitialAirspeedMps, ...
    "InitialPitchDeg", local_default_if_nan(opts.InitialPitchDeg, trim0.pitch_deg), ...
    "InitialFlightPathDeg", opts.InitialFlightPathDeg, ...
    "InitialElevatorDelta", initialDelta, ...
    "InitialThrottleCmd", trim0.throttle_cmd, ...
    "HiddenElevatorTrim", hiddenTrim, ...
    "MpcEnableTimeS", opts.MpcEnableTimeS, ...
    "MpcAuthorityScale", opts.MpcAuthorityScale, ...
    "ElevatorDevStepLimit", opts.ElevatorDeviationRateLimit, ...
    "ThrottleDevStepLimit", opts.ThrottleDeviationRateLimit, ...
    "TrustAltitudeM", opts.TrustAltitudeM, ...
    "TrustAirspeedMps", opts.TrustAirspeedMps, ...
    "TrustPitchDeg", opts.TrustPitchDeg, ...
    "TrustVzMps", opts.TrustVzMps, ...
    "TrustQDps", opts.TrustQDps, ...
    "TargetAltitudeM", opts.TargetAltitudeM, ...
    "TargetAirspeedMps", opts.TargetAirspeedMps, ...
    "TargetPitchDeg", trim0.pitch_deg, ...
    "UseTrimPitchReference", 1.0);

T = simResult.timeseries;
summary = local_diagnostics(T, physicalNom, trim0.throttle_cmd, opts);
writetable(summary, fullfile(outputRoot, "guarded_smoke_summary.csv"));
local_plot(T, physicalNom, trim0.throttle_cmd, fullfile(outputRoot, "guarded_smoke_curves.png"));

fprintf("\n[V13] cfg0 guarded smoke:\n");
disp(summary);
if summary.hard_fail
    fprintf("[V13] HARD FAIL -> stop here. Do not run Bayesopt or cfg1/cfg2.\n");
elseif summary.local_envelope_pass
    fprintf("[V13] PASS -> bridge is coherent and MPC stayed inside the v11 local ID envelope.\n");
else
    fprintf("[V13] SOFT FAIL -> plant stayed alive but local tracking is not yet acceptable. Tune only after inspecting this CSV.\n");
end

result = struct();
result.output_root = outputRoot;
result.bank_mat = string(bankMat);
result.hidden_trim = hiddenTrim;
result.physical_elevator_nominal = physicalNom;
result.initial_external_delta = initialDelta;
result.summary = summary;
result.timeseries = T;
save(fullfile(outputRoot, "guarded_smoke_result.mat"), "result", "opts");
end

function S = local_diagnostics(T, eNom, tNom, opts)
t = double(T.time_s(:));
h = double(T.altitude_m(:));
V = double(T.airspeed_mps(:));
pitch = double(T.pitch_deg(:));
vz = double(T.vz_up_mps(:));
q = double(T.q_dps(:));
ePhysical = double(T.elevator_cmd_norm(:));
th = double(T.throttle_norm(:));
bridgeE = double(T.bridge_elevator_error(:));
bridgeT = double(T.bridge_throttle_error(:));
steady = t >= min(opts.ScoreStartTimeS, max(t));
if nnz(steady) < 10, steady = isfinite(t); end
hRms = local_rms(h(steady) - opts.TargetAltitudeM);
vaRms = local_rms(V(steady) - opts.TargetAirspeedMps);
vzRms = local_rms(vz(steady));
qRms = local_rms(q(steady));
maxElevDev = max(abs(ePhysical - eNom), [], "omitnan");
maxThrDev = max(abs(th - tNom), [], "omitnan");
maxBridgeE = max(abs(bridgeE), [], "omitnan");
maxBridgeT = max(abs(bridgeT), [], "omitnan");
minH = min(h, [], "omitnan");
maxAbsPitch = max(abs(pitch), [], "omitnan");
hardFail = ~isfinite(minH) || minH < opts.HardFloorAltitudeM || ...
    ~isfinite(qRms) || qRms > opts.HardMaxQRmsDps || ...
    ~isfinite(maxAbsPitch) || maxAbsPitch > opts.HardMaxAbsPitchDeg || ...
    ~isfinite(maxBridgeE) || ~isfinite(maxBridgeT) || ...
    maxBridgeE > opts.MaxBridgeError || maxBridgeT > opts.MaxBridgeError;
envelopePass = ~hardFail && ...
    maxElevDev <= opts.ElevatorDeviationLimit + 0.005 && ...
    maxThrDev <= opts.ThrottleDeviationLimit + 0.005 && ...
    hRms <= opts.SmokeMaxAltitudeRmsM && ...
    vaRms <= opts.SmokeMaxAirspeedRmsMps && ...
    vzRms <= opts.SmokeMaxVzRmsMps && ...
    qRms <= opts.SmokeMaxQRmsDps;
S = table(minH, hRms, vaRms, vzRms, qRms, maxAbsPitch, maxElevDev, maxThrDev, ...
    maxBridgeE, maxBridgeT, logical(hardFail), logical(envelopePass), ...
    'VariableNames', {'min_altitude_m','steady_h_rms_m','steady_Va_rms_mps','steady_vz_rms_mps', ...
    'steady_q_rms_dps','max_abs_pitch_deg','max_physical_elevator_deviation','max_throttle_deviation', ...
    'max_bridge_elevator_error','max_bridge_throttle_error','hard_fail','local_envelope_pass'});
end

function local_plot(T, eNom, tNom, outFile)
fig = figure('Visible','off','Color','w','Position',[100 100 1300 1000]);
tl = tiledlayout(7,1,'Padding','compact','TileSpacing','compact');
t = T.time_s;
nexttile; plot(t,T.altitude_m); hold on; yline(T.target_altitude_m(1),'--'); grid on; ylabel('h m');
nexttile; plot(t,T.airspeed_mps); hold on; yline(T.target_airspeed_mps(1),'--'); grid on; ylabel('Va');
nexttile; plot(t,T.pitch_deg); grid on; ylabel('pitch deg');
nexttile; plot(t,T.vz_up_mps); yline(0,'--'); grid on; ylabel('vz');
nexttile; plot(t,T.q_dps); yline(0,'--'); grid on; ylabel('q dps');
nexttile; plot(t,T.elevator_cmd_norm,'DisplayName','physical actual'); hold on; yline(eNom,'--','DisplayName','physical nominal'); if any(isfinite(T.bridge_physical_elevator_cmd)), plot(t,T.bridge_physical_elevator_cmd,':','DisplayName','bridge expected'); end; grid on; ylabel('elevator'); legend('Location','best');
nexttile; plot(t,T.throttle_norm,'DisplayName','actual'); hold on; yline(tNom,'--','DisplayName','nominal'); if any(isfinite(T.mpc_throttle_to_plant)), plot(t,T.mpc_throttle_to_plant,':','DisplayName','to plant'); end; grid on; ylabel('throttle'); xlabel('time s'); legend('Location','best');
title(tl,'AirdropX v13 guarded cfg0 smoke');
exportgraphics(fig,outFile,'Resolution',160); close(fig);
end

function x = local_column(T, name)
if ismember(string(name), string(T.Properties.VariableNames))
    x = double(T.(char(name))(:));
else
    x = NaN(height(T),1);
end
end

function v = local_default_if_nan(v, fallback)
if ~isfinite(double(v)), v = double(fallback); end
end

function v = local_rms(x)
x = double(x(:)); x = x(isfinite(x));
if isempty(x), v = NaN; else, v = sqrt(mean(x.^2)); end
end

function paths = local_paths(projectRoot)
projectRoot = string(projectRoot);
if strlength(projectRoot) == 0
    thisDir = fileparts(mfilename("fullpath"));
    matlabDir = fileparts(thisDir);
    projectRoot = string(fileparts(matlabDir));
else
    matlabDir = fullfile(projectRoot, "matlab");
end
paths.projectRoot = char(projectRoot);
paths.matlabDir = char(matlabDir);
paths.mpcDir = char(fullfile(matlabDir, "mpc"));
paths.autoDir = char(fullfile(matlabDir, "mpc_auto"));
paths.sfuncDir = char(fullfile(matlabDir, "sfunc_jsbsim"));
end

function opts = local_options(varargin)
opts.ProjectRoot = "";
opts.IdentifiedMat = "matlab/results/mpc_auto_id_v11_clean_r1/identify/airdropx_identified_plants.mat";
opts.OutputRoot = "matlab/results/mpc_auto_smoke_cfg0_v13_guarded";
opts.PhysicalElevatorNominals = [];
opts.PredictionHorizon = 8;
opts.ControlHorizon = 3;
opts.StopTimeS = 30.0;
opts.ScoreStartTimeS = 10.0;
opts.InitialAltitudeM = 20.0;
opts.InitialAirspeedMps = 50.0;
opts.InitialPitchDeg = NaN;
opts.InitialFlightPathDeg = 0.0;
opts.TargetAltitudeM = 20.0;
opts.TargetAirspeedMps = 50.0;
opts.CalibrationStopTimeS = 0.5;
opts.CalibrationUseUntilS = 0.25;
opts.PreflightStopTimeS = 10.0;
opts.MpcEnableTimeS = 3.0;
opts.MpcAuthorityScale = 0.35;
opts.ElevatorDeviationLimit = 0.035;
opts.ThrottleDeviationLimit = 0.060;
opts.ElevatorDeviationRateLimit = 0.006;
opts.ThrottleDeviationRateLimit = 0.010;
opts.TrustAltitudeM = 5.0;
opts.TrustAirspeedMps = 4.0;
opts.TrustPitchDeg = 4.0;
opts.TrustVzMps = 2.5;
opts.TrustQDps = 4.0;
opts.OutputWeights = [8.0 5.0 0.05 3.0 4.0];
opts.MVWeights = [0.20 0.15];
opts.MVRateWeights = [8.0 4.0];
opts.HardFloorAltitudeM = 5.0;
opts.HardMaxQRmsDps = 10.0;
opts.HardMaxAbsPitchDeg = 30.0;
opts.MaxBridgeError = 0.01;
opts.SmokeMaxAltitudeRmsM = 2.0;
opts.SmokeMaxAirspeedRmsMps = 2.0;
opts.SmokeMaxVzRmsMps = 1.0;
opts.SmokeMaxQRmsDps = 1.5;
if mod(numel(varargin),2) ~= 0, error("Options must be name-value pairs."); end
for i=1:2:numel(varargin)
    name = string(varargin{i});
    if ~isfield(opts,name), error("Unknown option: %s",name); end
    opts.(name) = varargin{i+1};
end
end
