from pathlib import Path
root=Path(__file__).resolve().parents[1]
checks=[]
def ck(name,cond): checks.append((name,bool(cond)))
def txt(rel): return (root/rel).read_text(encoding='utf-8',errors='ignore')
mission=txt('matlab/airdrop/airdropx_wind_airdrop_mission_v131.m')
frac=txt('matlab/airdrop/airdropx_airdrop_fractional_release_v131.m')
cal=txt('matlab/phys_mpc/airdropx_phys_mpc_wind_disturbance_calibrate_v130.m')
solve=txt('matlab/phys_mpc/airdropx_phys_mpc_solve_disturbance_v130.m')
forecast=txt('matlab/phys_mpc/airdropx_phys_mpc_wind_forecast_v130.m')
runner=txt('run_wind_disturbance_airdrop_v131_D.ps1')
entry=txt('matlab/airdrop/airdropx_wind_airdrop_entry_v131.m')
finalize=txt('matlab/airdrop/airdropx_wind_airdrop_finalize_v131.m')
installer=txt('install_wind_disturbance_airdrop_v131.ps1')

# v1.3.0 wind-disturbance MPC contracts retained.
ck('real symmetric JSBSim gust calibration','+h' in cal and '-h' in cal and '(ep-em)/(2*h)' in cal)
ck('three wind calibration probes','[0.5 1.0 2.0]' in cal)
ck('disturbance condensed into QP','ctrl.Fdist*gvec' in solve)
ck('zero-disturbance solver equivalence','zero_disturbance_u_error' in cal and 'err<=1e-10' in cal)
ck('delta-wind causal forecast','delta_wind_pred_mps' in forecast and 'RateCap_mps2' in forecast)
ck('residual observer retained','dHat' in mission and 'ResidualObserverAlpha' in mission)
ck('identified gust removed before residual','prev.ctrl.Gw*dwObserved' in mission)
ck('residual reset on payload transition','observerHoldoff=1' in mission)
ck('instantaneous gust peak report-only','instantaneous_peak_primary_normalized' in mission and 'not a causal' in mission)
ck('post-gust recovery gates','carrier_post_gust_peak' in mission and 'carrier_gust_recovery' in mission)
ck('wind truth scoring-only','truth_wind_used_by_controller=0' in mission)

# v1.3.1 release-timing contracts.
ck('fractional scheduler exists',(root/'matlab/airdrop/airdropx_airdrop_fractional_release_v131.m').is_file())
ck('fractional release default enabled','opts.UseFractionalRelease (1,1) logical = true' in mission)
ck('scheduler has no truth-wind input','wind_truth' not in frac.lower() and 'scenarioName' not in frac)
ck('scheduler uses current measured state','vx_ground_mps' in frac and 'wind_est_mps' in frac and 'wind_rate_est_mps2' in frac)
ck('within-sample nonlinear split','step_continuous",u,cfgBeforeStep' in mission and 'step_continuous",u,cfg,opts.FuelScale' in mission)
ck('same held MPC command on both subsegments',mission.count('step_continuous",u,') >= 3)
ck('physical cfg transition at timer','cfg=cfgBeforeStep+1' in mission)
ck('warmstart rebased after timed drop','airdropx_phys_mpc_rebase_warmstart(sol.U,oldCtrl,newCtrl)' in mission)
ck('actual release state re-predicted','predAtRel=airdropx_airdrop_predict_impact_v121(relPredState)' in mission and 'release.predicted_impact_m(j)=predAtRel.impact_x_m' in mission)
ck('scheduler residual logged separately','scheduler_residual_m' in mission and 'release_phase_s' in mission)
ck('mixed-cfg prediction error not falsely scored','PredErrInf(k)=NaN' in mission)
ck('legacy sampled release ablation','legacy_sample_boundary' in mission and "Mode='wind_mpc_aware_sampled_release'" in runner and 'Fractional=$false' in runner)
ck('formal runner still has three controller modes',all(x in runner for x in ['wind_mpc_aware','legacy_mpc_aware','legacy_mpc_nowind']))
ck('formal 24 + calm ablation runner',runner.count('$jobs += [pscustomobject]') >= 4 and 'wind_mpc_aware_sampled_release' in runner)
ck('3-worker cap','$MaxParallel -gt 3' in runner)
ck('v131 entry forwards release option','UseFractionalRelease=opts.UseFractionalRelease' in entry)
ck('finalizer reports calm ablation','calm_sampled_over_fractional_rms' in finalize)
ck('installer deploys v131 MATLAB tree and runners',"Get-ChildItem -Path (Join-Path $Here 'matlab') -Recurse -File" in installer and 'run_wind_disturbance_airdrop_v131_D.ps1' in installer)
ck('no precompiled mex',not any(root.rglob('*.mexw64')))
ck('version correct','v1.3.1' in txt('VERSION.txt'))

for n,v in checks: print(('PASS' if v else 'FAIL')+': '+n)
print(f'\nTOTAL {sum(v for _,v in checks)}/{len(checks)} PASS')
raise SystemExit(0 if all(v for _,v in checks) else 1)
