from pathlib import Path
root=Path(__file__).resolve().parents[1]
checks=[]
def ck(name,cond): checks.append((name,bool(cond)))
def txt(rel): return (root/rel).read_text(encoding='utf-8',errors='ignore')
mission=txt('matlab/airdrop/airdropx_wind_airdrop_mission_v130.m')
cal=txt('matlab/phys_mpc/airdropx_phys_mpc_wind_disturbance_calibrate_v130.m')
solve=txt('matlab/phys_mpc/airdropx_phys_mpc_solve_disturbance_v130.m')
forecast=txt('matlab/phys_mpc/airdropx_phys_mpc_wind_forecast_v130.m')
runner=txt('run_wind_disturbance_airdrop_v130_D.ps1')
ck('v130 mission exists',(root/'matlab/airdrop/airdropx_wind_airdrop_mission_v130.m').is_file())
ck('real symmetric gust calibration','+h' in cal and '-h' in cal and '(ep-em)/(2*h)' in cal)
ck('three calibration probes','[0.5 1.0 2.0]' in cal)
ck('wind map Va sign audit','Gw(2)>=-0.20' in cal)
ck('disturbance condensed into QP','ctrl.Fdist*gvec' in solve)
ck('zero disturbance equivalence selftest','zero_disturbance_u_error' in cal and 'err<=1e-10' in cal)
ck('delta wind not absolute wind comment','absolute wind' in forecast.lower() and 'delta_wind_pred_mps' in forecast)
ck('wind rate cap 3','RateCap_mps2' in forecast and '3.0' in forecast)
ck('residual observer','dHat' in mission and 'ResidualObserverAlpha' in mission)
ck('subtract Gw observed wind before residual','prev.ctrl.Gw*dwObserved' in mission)
ck('observer reset on drop','observerHoldoff=1' in mission)
ck('truth not used by controller summary','truth_wind_used_by_controller=0' in mission)
ck('instantaneous peak retained','instantaneous_peak_primary_normalized' in mission)
ck('causal post gust gate','carrier_post_gust_peak' in mission and 'carrier_gust_recovery' in mission)
ck('original final tail gates retained','carrier_final' in mission and 'carrier_tail' in mission)
ck('24 mission runner','wind_mpc_aware' in runner and 'legacy_mpc_aware' in runner and 'legacy_mpc_nowind' in runner)
ck('3-worker cap','$MaxParallel -gt 3' in runner)
ck('calibration stage in runner','airdropx_phys_mpc_wind_disturbance_calibrate_v130' in runner)
windinit=txt('matlab/wind/airdropx_longitudinal_wind_estimator_init_v111.m'); ck('wind estimator frozen defaults','StepNisThreshold (1,1) double {mustBePositive} = 16.0' in windinit and 'StepImmediateNisThreshold (1,1) double {mustBePositive} = 64.0' in windinit and 'WindAccelerationSigma_mps2 (1,1) double {mustBePositive} = 1.00' in windinit)
ck('no precompiled mex',not any(root.rglob('*.mexw64')))
ck('version correct','v1.3.0' in txt('VERSION.txt'))
for n,v in checks: print(('PASS' if v else 'FAIL')+': '+n)
print(f'\nTOTAL {sum(v for _,v in checks)}/{len(checks)} PASS')
raise SystemExit(0 if all(v for _,v in checks) else 1)
