function [elevator_delta, throttle_cmd, delta_m_signal, h_err, u_pd, drop_trim_bias, u_total, u_out, saturated] = airdropx_pd_nw20_block(altitude_m, vz_up_mps, airspeed_mps, pitch_deg, mass_kg, drop_count, h_ref, Kp, Kd, u_limit, u_rate_limit, K_mass, bias_rate_limit, throttle_kp, throttle_fixed, throttle_alt_kp, throttle_vz_kd, v_ref_mps, drop_mass_signal_kg, initial_elevator_delta, pitch_ref_deg, pitch_kp, pitch_limit, pitch_rate_kd, pitch_rate_limit, dt_s)
%AIRDROPX_PD_NW20_BLOCK Simulink wrapper for the repository PD baseline.
% Use this inside a MATLAB Function block for the NW20 20m 4-drop task.

%#codegen

persistent state prev_drop_count
if nargin < 4 || isempty(pitch_deg)
    pitch_deg = 0.0;
end
if nargin < 7 || isempty(h_ref)
    h_ref = 20.0;
end
if nargin < 16 || isempty(throttle_alt_kp)
    throttle_alt_kp = 0.0;
end
if nargin < 17 || isempty(throttle_vz_kd)
    throttle_vz_kd = 0.0;
end
if nargin < 21 || isempty(pitch_ref_deg)
    pitch_ref_deg = 4.0;
end
if nargin < 22 || isempty(pitch_kp)
    pitch_kp = 0.0;
end
if nargin < 23 || isempty(pitch_limit)
    pitch_limit = 0.0;
end
if nargin < 24 || isempty(pitch_rate_kd)
    pitch_rate_kd = 0.0;
end
if nargin < 25 || isempty(pitch_rate_limit)
    pitch_rate_limit = 0.0;
end
if nargin < 26 || isempty(dt_s)
    dt_s = 1.0 / 120.0;
end
if nargin < 8 || isempty(Kp)
    gains = struct('Kp', 0.090, ...
                   'Kd', 0.220, ...
                   'u_limit', 0.50, ...
                   'u_rate_limit', 0.015, ...
                   'K_mass', 0.05, ...
                   'bias_rate_limit', 0.0005, ...
                   'throttle_kp', 0.040, ...
                   'throttle_fixed', 0.54, ...
                   'throttle_alt_kp', 0.0, ...
                   'throttle_vz_kd', 0.0, ...
                   'v_ref_mps', 45.0, ...
                   'pitch_ref_deg', 4.0, ...
                   'pitch_kp', 0.0, ...
                   'pitch_limit', 0.0, ...
                   'pitch_rate_kd', 0.0, ...
                   'pitch_rate_limit', 0.0, ...
                   'dt_s', 1.0 / 120.0);
else
    gains = struct('Kp', double(Kp), ...
                   'Kd', double(Kd), ...
                   'u_limit', double(u_limit), ...
                   'u_rate_limit', double(u_rate_limit), ...
                   'K_mass', double(K_mass), ...
                   'bias_rate_limit', double(bias_rate_limit), ...
                   'throttle_kp', double(throttle_kp), ...
                   'throttle_fixed', double(throttle_fixed), ...
                   'throttle_alt_kp', double(throttle_alt_kp), ...
                   'throttle_vz_kd', double(throttle_vz_kd), ...
                   'v_ref_mps', double(v_ref_mps), ...
                   'pitch_ref_deg', double(pitch_ref_deg), ...
                   'pitch_kp', double(pitch_kp), ...
                   'pitch_limit', double(pitch_limit), ...
                   'pitch_rate_kd', double(pitch_rate_kd), ...
                   'pitch_rate_limit', double(pitch_rate_limit), ...
                   'dt_s', double(dt_s));
end
if nargin < 19 || isempty(drop_mass_signal_kg)
    drop_mass_signal_kg = 300.0;
end
if nargin < 20 || isempty(initial_elevator_delta)
    initial_elevator_delta = 0.0;
end
if isempty(state)
    state = struct('u_prev', double(initial_elevator_delta), ...
                   'drop_trim_bias', 0.0, ...
                   'total_steps', 0.0, ...
                   'saturated_steps', 0.0, ...
                   'prev_pitch_deg', double(pitch_deg), ...
                   'pitch_initialized', 1.0);
end
if isempty(prev_drop_count)
    prev_drop_count = 0.0;
end

dc = max(0.0, double(drop_count) - prev_drop_count);
delta_m_signal = double(drop_mass_signal_kg) * dc;
prev_drop_count = double(drop_count);

[elevator_delta, throttle_cmd, state, diag] = airdropx_pd_controller( ...
    double(h_ref), double(altitude_m), double(vz_up_mps), double(airspeed_mps), ...
    delta_m_signal, double(mass_kg), state, gains, double(pitch_deg));

h_err = diag.e_h;
u_pd = diag.u_pd;
drop_trim_bias = diag.drop_trim_bias;
u_total = diag.u_total;
u_out = diag.u_out;
saturated = double(diag.saturated);
end
