from pathlib import Path
import re,sys
ROOT=Path(__file__).resolve().parents[1]
mission=(ROOT/'matlab/airdrop/airdropx_wind_airdrop_mission_v136p.m').read_text()
sinit=(ROOT/'matlab/avionics/airdropx_paper_sensor_init_v136p.m').read_text()
sstep=(ROOT/'matlab/avionics/airdropx_paper_sensor_step_v136p.m').read_text()
entry=(ROOT/'matlab/airdrop/airdropx_wind_airdrop_entry_v136p.m').read_text()
full=(ROOT/'run_paper_validation_v136p_D.ps1').read_text()
point=(ROOT/'run_paper_validation_point_v136p_D.ps1').read_text()
audit=(ROOT/'matlab/airdrop/airdropx_phys_mpc_base_equivalence_audit_v136p.m').read_text()
readme=(ROOT/'README_PAPER.md').read_text()
checks=[]
def ck(name,c): checks.append((name,bool(c)))
ck('formal paper sensor default', 'opts.UsePaperSensorModel (1,1) logical = true' in mission)
ck('nominal cargo default', 'opts.UseIndependentCargoTruth (1,1) logical = false' in mission)
ck('zero-bias sensor model', 'BiasSigma' not in sinit and 'random walk' not in sstep.lower())
ck('zero-mean measurements', '+p.Sigma' in sstep and 'randn' in sstep)
ck('controller state comes from sensor estimate', 'xCtrl=av.x_est' in mission)
ck('release uses estimated position/height', 'rs=struct("x_m",posCtrl,"h_m",xCtrl(1)' in mission)
ck('wind estimator uses measured Va/Vz/Vg', 'airdropx_longitudinal_wind_estimator_step_v111(est,VaMeas,VzMeas,VgMeas)' in mission)
ck('base MPC uses xCtrl', 'airdropx_phys_mpc_solve(baseCtrl,xCtrl,warm)' in mission)
ck('disturbance MPC uses xCtrl', 'airdropx_phys_mpc_solve_disturbance_v130(ctrl,xCtrl,gSeq,warm)' in mission)
ck('energy MPC uses xCtrl', 'airdropx_phys_mpc_solve_disturbance_v130(ctrlEnergy,xCtrl,gSeq,warm)' in mission)
ck('no solver consumes xTruth', not re.search(r'airdropx_phys_mpc_solve(?:_disturbance_v130)?\([^\n;]*xTruth', mission))
ck('truth release state separate', 'truth_release_x_m' in mission and 'release_x_est_m' in mission)
ck('truth-estimate time series pairs', 'h_truth_m' in mission and 'h_est_m' in mission and 'pos_n_truth_m' in mission and 'pos_n_est_m' in mission)
ck('truth leakage metrics explicit', 'jsbsim_state_truth_used_by_controller=0' in mission and 'jsbsim_navigation_truth_used_by_release=0' in mission)
ck('paper core separate from engineering gate', 'paper_core=struct()' in mission and 'engineering_gate=gate' in mission and '"engineering_pass"' in mission)
ck('actual impact model error metric', 'impact_prediction_error_m' in mission and 'max_impact_prediction_error_m' in mission)
ck('optional independent cargo sensitivity', '[switch]$IndependentCargoTruth' in point and 'UseIndependentCargoTruth=$indCargo' in point)
ck('ideal state ablation explicit', '[switch]$IdealStateFeedback' in point and 'UsePaperSensorModel=$paperSensor' in point)
ck('full runner forces paper sensors', 'UsePaperSensorModel=true' in full)
ck('full runner nominal cargo', 'UseIndependentCargoTruth=false' in full)
ck('same deterministic seed map', 'SensorNoiseSeed=(101:108)' in (ROOT/'matlab/airdrop/airdropx_wind_airdrop_manifest_v136p.m').read_text())
ck('hidden child windows full', "WindowStyle='Hidden'" in full)
ck('hidden child windows point', "WindowStyle='Hidden'" in point)
ck('missing marker does not force rebuild full', 'if($ForceBuild -or -not(Test-Path $mex)){' in full)
ck('missing marker does not force rebuild point', 'if(-not(Test-Path $mex)){' in point)
ck('base equivalence uses paper sensors', 'UsePaperSensorModel=true' in audit)
ck('paper assumptions documented', 'no fixed biases' in readme.lower() and 'JSBSim truth is used for RMS/peak/final/tail scoring' in readme)
ck('no precompiled binaries', not any(p.suffix.lower() in {'.mexw64','.dll','.exe'} for p in ROOT.rglob('*') if p.is_file()))
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS' if v else 'FAIL')+'  '+n)
print(f'\nstatic_contract_check_v136p: {len(checks)-len(failed)}/{len(checks)} PASS')
if failed:
    print('FAILED:'); [print(' - '+x) for x in failed]; sys.exit(1)
