from pathlib import Path
import re, sys
root=Path(__file__).resolve().parents[1]
h=(root/'matlab/wind/airdropx_wind_simulink_harness_v111.m').read_text(encoding='utf-8')
r=(root/'run_wind_estimator_validation_v113_D.ps1').read_text(encoding='utf-8')
i=(root/'install_wind_estimator_v113.ps1').read_text(encoding='utf-8').lower()
p=(root/'run_wind_estimator_point_v113_D.ps1').read_text(encoding='utf-8')
e=(root/'matlab/wind/airdropx_wind_estimation_entry_v111.m').read_text(encoding='utf-8')
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck('bad_exist_guard_removed', 'exist("sim","file")' not in h and "exist('sim','file')" not in h)
ck('simulink_real_probe', 'ver("simulink")' in h and 'license("test","Simulink")' in h and 'load_system("simulink")' in h)
ck('private_ic_retained', 'localWritePrivateIc' in h and 'wind_ic_v113_' in h)
ck('sfunction_add_block_has_no_function_name', not re.search(r'add_block\([^\n]*S-Function[^\n]*FunctionName',h))
ck('sfunction_parameters_set', 'set_param(plant,"Parameters",param);' in h)
ck('sfunction_function_set', 'set_param(plant,"FunctionName","sfun_airdropx_jsbsim");' in h)
idxp=h.find('set_param(plant,"Parameters",param);')
idxf=h.find('set_param(plant,"FunctionName","sfun_airdropx_jsbsim");')
ck('parameter_before_function_activation', idxp>=0 and idxf>idxp)
ck('sfunction_configuration_verified', 'SFUNCTION_CONFIGURED parameter_count=4' in h and 'SFunctionConfigurationFailed' in h)
ck('model_update_preflight', 'MODEL_UPDATE_START' in h and 'SimulationCommand","update"' in h and 'MODEL_UPDATE_DONE' in h)
ck('calm_serial_preflight', 'SERIAL HARNESS PREFLIGHT' in r and 'harness_preflight_failure.txt' in r)
ck('stderr_stdout_capture', 'ErrorSummary' in r and 'STDERR:' in r and 'STDOUT:' in r)
ck('v113_output_root', 'physics_mpc_v113_longitudinal_wind_validation' in r)
ck('v113_point_output_root', 'physics_mpc_v113_wind_point' in p)
ck('v113_report_label', 'Physics-MPC v1.1.3 longitudinal wind estimator validation' in e)
ck('truth_not_in_estimator_step', all(x not in (root/'matlab/wind/airdropx_longitudinal_wind_estimator_step_v111.m').read_text(encoding='utf-8') for x in ['windN','windE']))
ck('no_mex_cpp_payload', not any(x.suffix.lower() in {'.cpp','.mexw64'} for x in root.rglob('*') if x.is_file()))
ck('installer_no_rebuild', 'build_sfun' not in i and 'mex(' not in i)
ck('installer_v113_scripts', 'run_wind_estimator_validation_v113_d.ps1' in i and 'run_wind_estimator_point_v113_d.ps1' in i)
ck('failure_root_cause_recorded', (root/'tests/failure_root_cause_v112.txt').is_file())
ck('estimator_gate_values_unchanged', all(tok in e for tok in ['MaxNoiselessRmse_mps','MaxNoisyRmseMean_mps','MaxNoisyP95Mean_mps','MaxStepSettling90_s','MinNoiseReductionRatio']))
passed=sum(v for _,v in checks)
for n,v in checks: print(('PASS' if v else 'FAIL'),n)
print(f'TOTAL {passed}/{len(checks)} PASS')
sys.exit(0 if passed==len(checks) else 1)
