function result = airdropx_mpc_outer_pd_run_optimized_warmup(varargin)
%AIRDROPX_MPC_OUTER_PD_RUN_OPTIMIZED_WARMUP Conservative optimized run.
%
% This preset prioritizes altitude hold and pitch over airspeed. It uses a
% 20 s warm-up, then exports and evaluates the following 30 s window.

opts = local_options(varargin{:});

result = airdropx_mpc_outer_pd_run_closed_loop( ...
    "OutputRoot", opts.OutputRoot, ...
    "StopTimeS", opts.StopTimeS, ...
    "WarmupTimeS", opts.WarmupTimeS, ...
    "TargetAltitudeM", opts.TargetAltitudeM, ...
    "TargetAirspeedMps", opts.TargetAirspeedMps, ...
    "TargetPitchDeg", opts.TargetPitchDeg, ...
    "DropMode", opts.DropMode, ...
    "CarpTargetNorthM", opts.CarpTargetNorthM, ...
    "CarpTargetEastM", opts.CarpTargetEastM, ...
    "CarpReleaseWindowS", opts.CarpReleaseWindowS, ...
    "CarpIntervalS", opts.CarpIntervalS, ...
    "CarpDropTotal", opts.CarpDropTotal, ...
    "CarpMinSafeAltitudeM", opts.CarpMinSafeAltitudeM, ...
    "CarpTargetOffsetNorthM", opts.CarpTargetOffsetNorthM, ...
    "CarpTargetOffsetEastM", opts.CarpTargetOffsetEastM, ...
    "CarpReleaseDelayS", opts.CarpReleaseDelayS, ...
    "BallisticKDragScale", opts.BallisticKDragScale, ...
    "BallisticKDrag", opts.BallisticKDrag, ...
    "InitialAirspeedMps", opts.InitialAirspeedMps, ...
    "InitialAltitudeM", opts.InitialAltitudeM, ...
    "InitialPitchDeg", opts.InitialPitchDeg, ...
    "InitialFlightPathDeg", opts.InitialFlightPathDeg, ...
    "InitialHeadingDeg", opts.InitialHeadingDeg, ...
    "InitialElevatorDelta", opts.InitialElevatorDelta, ...
    "InitialThrottleCmd", opts.InitialThrottleCmd, ...
    "ControlAltitudeBiasM", opts.ControlAltitudeBiasM, ...
    "ConfigOverrides", opts.ConfigOverrides, ...
    "RecreateModel", opts.RecreateModel, ...
    "DisableVRForBatch", opts.DisableVRForBatch, ...
    "ShowPlots", opts.ShowPlots);
end

function opts = local_options(varargin)
opts.OutputRoot = "";
opts.StopTimeS = 30.0;
opts.WarmupTimeS = 20.0;
opts.TargetAltitudeM = 20.0;
opts.TargetAirspeedMps = 50.0;
opts.TargetPitchDeg = 4.0;
opts.DropMode = 2.0;
opts.CarpTargetNorthM = 1525.0;
opts.CarpTargetEastM = 0.0;
opts.CarpReleaseWindowS = 0.05;
opts.CarpIntervalS = 0.0084;
opts.CarpDropTotal = 4.0;
opts.CarpMinSafeAltitudeM = 15.0;
opts.CarpTargetOffsetNorthM = [0.8; 1.6; 2.4; 3.8];
opts.CarpTargetOffsetEastM = zeros(4, 1);
opts.CarpReleaseDelayS = 0.0;
opts.BallisticKDragScale = 1.0;
opts.BallisticKDrag = NaN;
opts.InitialAirspeedMps = 50.0;
opts.InitialAltitudeM = 20.0;
opts.InitialPitchDeg = 4.0;
opts.InitialFlightPathDeg = 0.0;
opts.InitialHeadingDeg = -0.15;
opts.InitialElevatorDelta = -0.193;
opts.InitialThrottleCmd = 0.507;
opts.ControlAltitudeBiasM = 0.0;
opts.ConfigOverrides = [];
opts.RecreateModel = true;
opts.DisableVRForBatch = true;
opts.ShowPlots = true;

if mod(numel(varargin), 2) ~= 0
    error("Options must be name-value pairs.");
end

for i = 1:2:numel(varargin)
    name = string(varargin{i});
    value = varargin{i + 1};
    if ~isfield(opts, name)
        error("Unknown option: %s", name);
    end
    opts.(name) = value;
end
end
